# Generated by Django 2.1 on 2018-08-18 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hocit.models
import markupfield.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('notes', markupfield.fields.MarkupField(rendered_field=True)),
                ('notes_markup_type', models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default=None, max_length=30, null=True)),
                ('_notes_rendered', models.TextField(editable=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', markupfield.fields.MarkupField(rendered_field=True)),
                ('body_markup_type', models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default=None, max_length=30, null=True)),
                ('attached_file', models.FileField(upload_to=hocit.models.note_file_path)),
                ('_body_rendered', models.TextField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_notes', to='hocit.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overview', markupfield.fields.MarkupField(rendered_field=True)),
                ('overview_markup_type', models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown'), ('ReST', 'ReST')], default=None, max_length=30, null=True)),
                ('_overview_rendered', models.TextField(editable=False)),
                ('assigned_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hocit.Actor')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hocit.Report'),
        ),
    ]
